name: Compile LaTeX document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document (using latexmkrc)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: latexmk
          args: -interaction=nonstopmode -halt-on-error
      

      - name: Update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/report.pdf"
          tag: "latest"
          name: "Report PDF"
          body: "Automatic build of the latest report version."
          allowUpdates: true
          removeArtifacts: true
          token: ${{ secrets.RELEASE_TOKEN }}