name: Compile LaTeX document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document (using latexmkrc)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: latexmk
          args: -interaction=nonstopmode -halt-on-error

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Raport-Zespolowy-PDF
          path: build/main.pdf